Documentation/DocumentationAdmonition:
  Description: Reports documentation admonitions
  Enabled: false
  Severity: Warning

Naming/QueryBoolMethods:
  Description: Reports boolean properties without the `?` suffix
  Enabled: false
  Severity: Convention
